palcera_theme.settings:
  type: theme_settings
  label: "PalceraTheme settings"
  mapping:
    scheme:
      type: string
      label: Color scheme
      constraints:
        Choice:
          # @see \Drupal\palcera_theme\Hook\ThemeHooks::themeSettingsFormAlter()
          - light
          - dark
